### ISSUE TITLE
Taking Attendance Not Working

### ISSUE THREAD

**Issue by StevenMonty** [pittktp/ktp-react#33]
When taking attendance, clicking "Not here" on a brother removes another random brother from the list but not the one clicked. While revisiting this feature, I think it would be more user friendly to replace "Not Here" with "Here" so you don't have to try and identify who is missing rather than who is present.

**Comment by ZvontyFlugence** [comment]
Most recent push fixed this issue, still needs to be deployed. I agree that it would be more user friendly to use 'Here' instead of 'Not Here', however, that would require a complete restructuring of how the attendance form works and how the API handles taking attendance. Due to this, I will open a new issue as an enhancement to tackle this.
